const cats = ['https://ichef.bbci.co.uk/images/ic/720x405/p0517py6.jpg',
	'https://ae01.alicdn.com/kf/HTB1gfQdb9BYBeNjy0Feq6znmFXaO/2017-30x25CM-The-Scottish-Fold-Cat-Favorites-Diamond-Embroidery-DIY-Creative-Home-Decor-1PCS.jpg_640x640.jpg',
	'https://i.redd.it/d6hxgsaivlu21.jpg',
	'https://i.imgur.com/hGiJyW0.jpg',
	'https://i.kym-cdn.com/photos/images/newsfeed/001/384/545/7b9.jpg',
	'https://cms.hostelbookers.com/hbblog/wp-content/uploads/sites/3/2012/02/refer-e1329931959958.jpg',
	'http://getwallpapers.com/wallpaper/full/0/a/1/49041.jpg',
	'https://cdn.wallpapersafari.com/9/12/rqdhvH.jpg',
	'https://i.redd.it/gauywc5rb5i21.jpg',
	'https://i.redd.it/toyl3goe44l21.jpg',
	'https://imgur.com/ETFS5wI.jpg',
	'https://i.redd.it/uykfl6nxaq231.jpg',
	'https://i.imgur.com/PwDy5pQ.jpg',
	'https://i.imgur.com/MxaAlri.png',
	'https://i.imgur.com/PsfzwLp.png',
	'https://i.imgur.com/oyVSzkJ.png',
	'https://i.imgur.com/ysjM1KC.png',
	'https://i.imgur.com/mDmmzaZ.png',
	'https://i.imgur.com/s8dUeYJ.png',
	'https://i.imgur.com/Z7b7ITC.png',
	'http://suptg.thisisnotatrueending.com/archive/10150465/images/1275204772405.jpg',
	'https://i.imgur.com/WptoeL8.png',
	'https://i.imgur.com/DL1M0S1.jpg',
	'https://i.imgur.com/6YXGVoz.jpg',
	'https://i.imgur.com/b8OZrQL.jpg',
];
export default cats;
